FROM python:3.8-alpine

ENV LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8

RUN set -x \
  && apk add --no-cache --virtual .build-deps \
    build-base \
    libffi-dev \
    libxml2-dev \
    mariadb-connector-c-dev \
    openldap-dev \
    python3-dev \
    xmlsec-dev \
    yarn \
    cargo \
  && apk add --no-cache --virtual .run-deps \
    mariadb-connector-c \
    postgresql-client \
    py3-gunicorn \
    py3-psycopg2 \
    xmlsec \
    tzdata

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

# Get application dependencies
RUN set -x \
  && pip install --upgrade pip \
  && pip install -r requirements.txt

ENV \
    FLASK_DEBUG=1 \
    FLASK_APP=/app/powerdnsadmin/__init__.py

COPY --chown=root:root --chmod=0755 docker/entrypoint.dev.sh /usr/local/bin/entrypoint

ENTRYPOINT [ "entrypoint" ]

CMD [ "dev" ]
